# Generated by Django 4.1.7 on 2023-08-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuelstations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=128, verbose_name='Station Name')),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('state', models.CharField(max_length=32, verbose_name='State')),
            ],
        ),
    ]
